# Generated by Django 5.2.4 on 2026-01-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("dob", models.DateField(blank=True, null=True)),
                ("mobile", models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name="brand",
            name="country",
        ),
    ]
