# Generated by Django 5.2.4 on 2026-01-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_siteuser_remove_brand_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
