# Generated by Django 5.2.4 on 2026-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_siteuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteuser",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
