# Generated by Django 5.2.4 on 2026-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_review_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
