# Generated by Django 5.2.4 on 2026-02-22 11:08

from django.db import migrations


import uuid

def generate_invoice_numbers(apps, schema_editor):
    Order = apps.get_model('pages', 'Order')
    for order in Order.objects.all():
        order.invoice_number = f"INV-{uuid.uuid4().hex[:8].upper()}"
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_order_invoice_number"),
    ]

    operations = [
        migrations.RunPython(generate_invoice_numbers),
    ]
