# Generated by Django 5.2.4 on 2026-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_auto_20260222_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=20, unique=True, default=""),
            preserve_default=False
        ),
    ]
